### PR TITLE
tslint changes

### PR DESCRIPTION
**Pull request by LunarMist**
The ~~two~~ one changes:
- Use LF instead of CRLF
- ~~Use 2 spaces instead of a tab~~

Normally, it's best to extend a popular ruleset (e.g. microsoft's or airbnb's), but with a project already this large, it's rather impractical to make those changes with how many errors there would be.

### CODE REVIEW

**Comment by BytewaveMLP** [comment]
Not sure how I feel about 2-space indentation; honestly, if we're going to spaces, I'd at least prefer 4.

LF I'll agree with, though. Just need to make sure everyone has `core.autocrlf` set to `input`, or TSLint will yell at them.

**Comment by liamwhite** [comment]
:+1: for 2 space

**Comment by Stubenhocker1399** [comment]
Is it possible to not affect git blame?

**Comment by liamwhite** [comment]
[Yes](https://coderwall.com/p/x8xbnq/git-don-t-blame-people-for-changing-whitespaces-or-moving-code)

**Comment by LunarMist** [comment]
What's the consensus on 2 vs 4 spaces then? Maybe at this rate we should just use the tabs LOL

**Comment by BytewaveMLP** [comment]
**Poll:**

👍 - 2 spaces
👎 - 4 spaces
❤️ - Leave tabs

**Comment by blackhole12** [comment]
pinging @LunarMist @Stubenhocker1399 for poll

**Comment by mathieucaroff** [comment]
I usually prefer space. I'd like to suggest the unpopular choice of 3 spaces, as a compromise between 2 and 4, because two spaces it too small for me to properly see the indent, and 4 spaces is wider than necessary, thus using more (precious) horizontal space than needed.

Soo, 👀 for 3 spaces in @BytewaveMLP 's poll.

**Comment by BytewaveMLP** [comment]
Chaotic neutral. I like you.

**Comment by LunarMist** [comment]
Seems like we can't decide on tabs or spaces. So we leave it as-is then (tabs). The only change would be CRLF -> LF

**Comment by BytewaveMLP** [comment]
My proposal for a sane `.editorconfig` matching these rules:
```ini
root = true

[*]
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
charset = utf-8

[*.{js,ts}]
indent_style = tab

[*.json]
indent_style = space
indent_size = 2
```

**Pull request merged**
