### PR TITLE
Security: Don't allow default secret/token config parameters

### PR DESCRIPTION
**Pull request by BytewaveMLP**
Currently, the README doesn't document the use of the `secret` and `token` config parameters, and just asks you to randomize them. The README doesn't state their purpose, and the app doesn't care if these values are present or secure.

This PR adds a check at initialization time to ensure these config values are set and randomized. If an insecure value for one of these config parameters is detected (unset, default, <16 characters long) and the app is not running in development or test mode, a verbose error message will be displayed upon startup informing server operators about changing these values, and the app will exit. It also adds a note to the README about this config value for newcomers.

### CODE REVIEW

**Comment by BytewaveMLP** [comment]
Question: Do we want to use the random.org method of generating tokens, or use system randomness by means of a PowerShell expression? Seems the following should work, and be less cumbersome than combining 4 16char strings:

```ps
-join ((48..57) + (65..90) + (97..122) | Get-Random -Count 64 | % {[char]$_})
```

but it also requires people to use PowerShell.

**Comment by Tschrock** [comment]
I think it's safe to assume they will have node installed, in which case the simplest method would be
```bash
node -e "console.log(require('crypto').randomBytes(64).toString('base64'))"
```

**Comment by BytewaveMLP** [comment]
True. Could even take it a step further:

```js
const c=require('crypto');let r=()=>c.randomBytes(64).toString('base64');const f=require('fs');const j=JSON.parse(fs.readFileSync('./config.json'));j['secret']=r();j['token']=r();fs.writeFileSync('./config.json',JSON.stringify(j,!1,2));
```

**Comment by Tschrock** [comment]
You could, but at that point you should probably make a tools script for it - or even just do it directly in config.ts when the value is detected to be empty or default

**Comment by BytewaveMLP** [comment]
That's a good point... I really could just generate it myself. But I liked yelling at the user. :C

**Comment by BytewaveMLP** [comment]
Thinking about it, that might screw with whatever indent style they use for their config. May be best to let them handle it.

**Pull request merged**
